app:
  name: random-shopper
  repository: "szymen"

namespace_name: random-shopper-namespace

service_list:

  customer-management-api:
    image: "random-shopper-customer-management"
    version: "latest"
    port: 5000
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
    config_map:
      APP_MODE: web
      PYTHONPATH: /app
      FLASK_APP: app:create_app
      SQLALCHEMY_DATABASE_URI: postgresql://customer:customer@db:5432/customer_mgmt
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      LOG_LEVEL: INFO
    secrets:
      database_password: "supersecretpassword"

  purchases-kafka-consumer:
    image: "random-shopper-customer-management"
    version: "latest"
    config_map:
      APP_MODE: kafka
      SQLALCHEMY_DATABASE_URI: postgresql://customer:customer@db:5432/customer_mgmt
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      LOG_LEVEL: DEBUG
    secrets:
      database_password: "anothersecretpassword"

  customer-face:
    image: "random-shopper-customer-face"
    version: "latest"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
    port: 5001
    config_map:
      APP_MODE: web
      PYTHONPATH: /app
      FLASK_APP: app:create_app
      SQLALCHEMY_DATABASE_URI: postgresql://customer:customer@db:5432/customer_mgmt
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      LOG_LEVEL: INFO
      CUSTOMER_MANAGEMENT_URL: http://customer-management-api:5000

db:
  enabled: true
  image: postgres:16-alpine
  imagePullPolicy: IfNotPresent
  postgresUser: customer
  postgresPassword: customer
  postgresDb: customer_mgmt
  persistence:
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /var/lib/postgresql/data

kafka:
  enabled: true
  image: apache/kafka:4.1.2
  imagePullPolicy: IfNotPresent
  persistence:
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /var/lib/kafka/data

kafkaUi:
  enabled: true
  image: provectuslabs/kafka-ui:latest
  imagePullPolicy: IfNotPresent

