"""add users table and refactor purchases

Revision ID: fae1b369041d
Revises: 
Create Date: 2026-03-19 16:59:06.049359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae1b369041d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_purchases_userid'))
        batch_op.drop_index(batch_op.f('ix_purchases_username'))
        batch_op.create_index(batch_op.f('ix_purchases_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchases_user_id'))
        batch_op.create_index(batch_op.f('ix_purchases_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_userid'), ['userid'], unique=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
