{{- range $sub_service_name, $sub_service_values := $.Values.service_list }}

{{- if $sub_service_values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sub_service_name }}-secret
  namespace: {{ $.Values.namespace_name }}
  labels:
    app_name: {{ $sub_service_name }}
    chart_name: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
type: Opaque
data:
  {{- $sortedKeys := keys $sub_service_values.secrets | sortAlpha -}}
  {{- range $key := $sortedKeys }}
  {{ $key | replace "." "_" }}: {{ get $sub_service_values.secrets $key | b64enc }}
  {{- end }}

{{- end }} {{/* if .Values.secrets */}}
{{- end }} {{/* for sub_svc */}}
