version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
      POSTGRES_DB: customer_mgmt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.1.2
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  web:
    build: .
    volumes:
      - /Users/szymon.maslowski/code/random-shopper/customer-management:/app
    environment:
      APP_MODE: web
      SQLALCHEMY_DATABASE_URI: postgresql://customer:customer@db:5432/customer_mgmt
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LOG_LEVEL: INFO
    ports:
      - "5000:5000"
    depends_on:
      - db

  consumer:
    build: .
    environment:
      APP_MODE: kafka
      SQLALCHEMY_DATABASE_URI: postgresql://customer:customer@db:5432/customer_mgmt
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LOG_LEVEL: INFO
    depends_on:
      - db
      - kafka

volumes:
  pgdata:

